---
- name: Hello world Juniper Junos
  hosts: vlab 
  connection: local
  # become: False
  gather_facts: False

################################
# vars prompt
################################
  vars_prompt:
    - name: apply_config
      prompt: "apply the configuration to the devices (yes/no - don't apply apply)"
      private: no
   
################################
# Roles
# note order is important
################################

  roles:
    - Juniper.junos
    - test_juniper_config

################################
# Tasks
################################
#  tasks:
#  
#    - name: get device facts
#      juniper_junos_facts:
#        host: "{{ host_ip }}"
#        savedir: "{{ playbook_dir }}"
#    - name: print junos version
#      debug:
#        var: junos.version
