---
# tasks file for Memcached
- name: hello world!
  debug:
    msg: "Hello World!"

#- name: Ensure the default Namespace exists.
#  community.kubernetes.k8s:
#    api_version: v1
#    kind: Namespace
#    name: default
#    state: present

- name: start memcached
  community.kubernetes.k8s:
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-memcached'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: memcached
        template:
          metadata:
            labels:
              app: memcached
          spec:
            containers:
            - name: memcached
              command:
              - memcached
              - -m=64
              - -o
              - modern
              - -v
              image: "docker.io/memcached:1.4.36-alpine"
              ports:
                - containerPort: 11211
