---
# tasks go here 
- name: Show interfaces 
  junos_command:
    commands:
      - "show interfaces terse"
    display: "json"
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"
  register: show_interface_output

- name: Debug interface output
  debug:
    var: show_interface_output

- name: show configuration 
  junos_command:
    commands:
      - "show configuration | display json"
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"
  register: show_configuration_output

- name: Debug show_configuration_output 
  debug:
    var: show_configuration_output
