---
# tasks go here 
- name: Show interfaces 
  junos_command:
    commands:
      - "show interfaces terse"
    display: "json"
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"
  register: show_interface_output

- name: Debug interface output
  debug:
    var: show_interface_output

- name: show configuration 
  junos_command:
    commands:
      - "show configuration"
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"
  register: show_configuration_output

- name: Debug show_configuration_output 
  debug:
    var: show_configuration_output
  when: show_config is defined

- name: set description for interface ge-0/0/4
  junos_config:
    lines:
      - set interfaces ge-0/0/4 unit 0 description "hello world"
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"
  register: config_output

- name: debug config_output
  debug:
    var: config_output

- name: set fact new cloud client config
  set_fact:
    new_cloud_client_config_file: "{{ playbook_dir }}/new_cloud_client_config"

- name: generate config template
  template:
    src: "{{ role_path }}/templates/add_cloud_client.j2"
    dest: "{{ new_cloud_client_config_file }}"
  delegate_to: localhost

- name: apply config template to vmx
  junos_config:
    src: "{{ new_cloud_client_config_file }}"
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"

    
