apiVersion: v1
kind: Pod
metadata:
  name: ansible-redis
  labels: # Labels to be applied to the Pods in this deployment
    app: redis
spec:
  containers:
  - name: ubuntu
    # replace image with whatever Ubuntu image you want
    image: docker.apple.com/pdt/deploy:0.1
#    command:
#      - redis-server
#      - "/redis-master/redis.conf"
#    env:
#    - name: MASTER
#      value: "true"
#    ports:
#    - containerPort: 6380
#    resources:
#      limits:
#        cpu: "0.1"
#    volumeMounts:
#    - mountPath: /redis-master-data
#      name: data
#    - mountPath: /redis-master
#      name: config
#  volumes:
#    - name: data
#      emptyDir: {}
#    - name: config
#      configMap:
#        name: nh-redis-config
#        items:
#        - key: redis-config
#          path: redis.conf
#---
#apiVersion: v1
#kind: Service        # Type of Kubernetes resource
#metadata:
#  name: nh-redis-svc # Name of the Kubernetes resource
#  labels:            # Labels that will be applied to this resource
#    app: redis
#    role: master
#    tier: backend
#spec:
#  ports:
#  - port: 6380       # Map incoming connections on port 6379 to the target port 6379 of the Pod
#    targetPort: 6380
#  selector:          # Map any Pod with the specified labels to this service
#    app: redis
#    role: master
#    tier: backend

