---
# tasks file for test_juniper_config
#
- name: convert enable_debug to boolean
  set_fact:
    enable_debug: "{{ enable_debug | bool }}"

- name: convert apply_config to boolean
  set_fact:
    apply_config: "{{ apply_config | bool }}"

- name: get device facts
  juniper_junos_facts:
    host: "{{ host_ip }}"
    savedir: "{{ playbook_dir }}"

- name: dump junos version
  debug:
    var: junos.version
  when: enable_debug

- name: dump apply_config
  debug:
    var: apply_config
  when: enable_debug

- name: test config preview
  juniper_junos_config:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    load: "set"
    diff: true
    commit: "{{ apply_config }}" 
    # retrieve: candidate
    return_output: true
    lines:
      - 'set interfaces ge-0/0/4 unit 0 description "hello world again"'
  register: response

- name: dump config preview response
  debug:
    # var: response.diff_lines
    var: response

- name: set configure_interface_file
  set_fact:
    configure_interface_file: "{{ playbook_dir }}/configure_interfaces_{{ ansible_host }}"

- name: dump configure_interface_file
  debug:
    var: configure_interface_file
  when: enable_debug

- name: apply j2 template
  template:
    src: "{{ role_path }}/templates/configure_interfaces.j2"
    dest: "{{ configure_interface_file }}"
  delegate: localhost

- name: apply the config interface template to the router
  juniper_junos_config:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    load: "set"
    diff: true
    commit: "{{ apply_config }}"
    return_output: true
    src: "{{ configure_interface_file }}"
  register: set_response

- name: dump config response
  debug:
    var: set_response
...
