---
# tasks go here 
- name: Show interfaces 
  eos_command:
    commands:
      - "show interfaces description" 
    provider:
      username: "{{ USERNAME }}"
      password: "{{ PASSWORD }}"
      host: "{{ host_ip }}"


