---
# tasks go here 
- name: Show interfaces 
  eos_command:
    commands:
      - "show interfaces description" 
    provider:
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      host: "{{ host_ip }}"
  register: show_interface_output

- name: Debug interface output
  debug:
    var: show_interface_output


