---
# tasks go here 
- name: Show interfaces 
  eos_command:
    commands:
      - "show interfaces description" 
    provider:
      username: "{{ ANSIBLE_NET_USERNAME }}"
      password: "{{ ANSIBLE_NET_PASSWORD }}"
      host: "{{ host_ip }}"


