---
# tasks file for get_aws_vpcs
- name: invoke aws cli to retrieve vpcs
  shell: "aws ec2 describe-vpcs"
  register: aws_get_vpcs_out

- name: reformat aws_get_vpcs_out to json fact
  set_fact:
    list_of_vpcs: "{{ aws_get_vpcs_out.stdout | from_json }}"

- name: dump aws vpcs
  debug:
    var: list_of_vpcs 
...
