---
- name: Hello world 
  hosts: arista 
  connection: local
  # become: False
  gather_facts: False

  # note order is important

################################
#Roles
################################

  roles:
    - hello_world 
