---
- name: sample-netplan dns update using lineinfile 
  hosts: localhost
  connection: local
  gather_facts: False
#  vars:
#     net_plan_file: "/home/vagrant/nh_automation/ansible/ubuntu_related/netplan_dns_update/99-netcfg-vmware.yaml"
#     contents: "{{ lookup('file', '{{ net_plan_file }}') }}"
  vars:
    new_dns_config:
      network:
        ethernets:
          ens160:
            nameservers:
              addresses: ['17.7.7.7', '17.8.8.8']
    
  tasks:
    - name: Test whether netplan file is present
      stat:
        path: "/home/vagrant/nh_automation/ansible/ubuntu_related/netplan_dns_update/99-netcfg-vmware.yaml"
      register: stat_out 

    - name: dump stat output
      debug:
        var: stat_out.stat.exists

    - name: read in vars from netplan file
      include_vars:
        file: "/home/vagrant/nh_automation/ansible/ubuntu_related/netplan_dns_update/99-netcfg-vmware.yaml"
        name: netplan_config

    - name: dump new dns_servers
      debug:
        msg: "{{ new_dns_config }}"

    - name: dump the file contents
      debug:
        var: netplan_config.network

    - name: revise netplan_config
      set_fact:
        netplan_config: "{{ netplan_config | combine( new_dns_config, recursive=true) }}"

    - name: dump the updated netplan_config 
      debug:
        var: netplan_config
        
    - name: write out a new netplan file
      template:
        src: empty_netplan.j2
        dest: new_netplan.yaml
...


  

              
