---
gcp_networks:
  neteng-test-gcp:
    type: "gcp"
    region: "us-east4"
    description: "neteng-test-gcp"
    network_prefixes:
      - "10.130.0.0/24"
    bgp_config:
      as_number: 64568

  can-automation-test-gcp:
    type: "gcp"
    region: "us-east4"
    description: "can-automation-test-gcp"
    network_prefixes:
     - "10.130.1.0/27"
    bgp_config:
      as_number: 64568
...        
